name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "Your_password123"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "bash -c 'echo > /dev/tcp/localhost/1433'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build
        run: dotnet build SqlSchemaDef.sln -c Release

      - name: Test
        env:
          SQLSCHEMADEF_TEST_CONNECTION_STRING: "Server=localhost,1433;User Id=sa;Password=Your_password123;Encrypt=False;TrustServerCertificate=True;Initial Catalog=master"
        run: dotnet test SqlSchemaDef.sln -c Release

